### ISSUE TITLE
forgotPassword API response body is null 

### ISSUE THREAD

**Issue by Vitroxyn** [TheMorpheus407/BattleOfAI#10]
The [forgotPassword API](https://iam.battleofai.net/api/iam/forgotPassword) should also indicates if a call has resulted in a success, like most endpoints in the [Accountmanagement Battle of AI API](https://iam.battleofai.net/api/).

**Comment by TheMorpheus407** [comment]
If there was feedback, attackers could gain intelligence whether an email or username is taken or not. That's why this point is not giving feedback to the frontend.
