### ISSUE TITLE
Storing the username and password in a file that is listed in the .gitignore

### ISSUE THREAD

**Issue by ndsvw** [TheMorpheus407/BattleOfAI#11]
Sooner or later, someone will publish his/her code on GitHub and forgets removing the username and the password out of it.

**A possibility to solve this problem:**
1. creating a new file that contains the login information only.
2. write an explanation somewhere -> The user has to fill out his/her login information in that new file.
3. adding this new file in the .gitignore
4. modifying files like "CORE_stupid_demo_ai.py" so that they try to get the login information first by importing (py-file) or reading (txt-file) the file with the login information.

**Why this should work:**
If the login information are stored in a file that is listed in the .gitignore file:
1) If the user pushes the whole BOAI folder, the login information stay on his/her PC.
2) If the user uploads the "CORE_stupid_demo_ai.py" only, the login information are not published

**Comment by Scriptim** [comment]
[.env files](https://pypi.org/project/python-dotenv/ "python-dotenv") exist for just that purpose
