### ISSUE TITLE
Implementation of the API for Scala

### ISSUE THREAD

**Issue by Vitroxyn** [TheMorpheus407/BattleOfAI#12]
I implemented the [Games](https://games.battleofai.net/api/), Games Query and [Iam](https://iam.battleofai.net/api/) API for Scala. 

The library is hosted here: https://gitlab.com/vitrox/battle-of-ai-api

I would appreciate a notice with the link to the library in the README, it would be helpful for other Scala users so they don't have to write their own implementation.

**Comment by ghost** [comment]
Closed because no usage example was implemented.
