### ISSUE TITLE
Extend API to get Player Name by Player ID

### ISSUE THREAD

**Issue by theblaggy** [TheMorpheus407/BattleOfAI#22]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I don´t no whom I´m playing against.

**Describe the solution you'd like**
I think the API should be extended in a way, that you can get the player name by the player ID.

**Describe alternatives you've considered**
I don´t think that there is an alternative solution for this problem.

**Comment by ghost** [comment]
Hey, 
didn't you see the issue templates?
Please use the "Feature request" template!

**Comment by theblaggy** [comment]
Sorry I accidentally deleted the headings, anyhow I´ve used the template

**Comment by the-blaggyS** [comment]
Sorry I accidentally deleted the headings, anyhow I´ve used the template.

**Comment by ghost** [comment]
This is not possible because of data protection.
