### ISSUE TITLE
Incorrect game statistics

### ISSUE THREAD

**Issue by Scriptim** [TheMorpheus407/BattleOfAI#23]
**Describe the bug**
I let my AI play two games against itself. According to my statistics, "I" won all games.

![Your CoRe stats](https://user-images.githubusercontent.com/13003924/46230885-45374580-c36a-11e8-9b89-2036dba4595c.png)

**To Reproduce**
1. Let an AI play against itself

**Expected behavior**
According to my math knowledge, the ratio between wins and losses should be 50:50.

**Additional context**
Game IDs: [223](https://battleofai.net/game.html?id=223 "Game 223") & [224](https://battleofai.net/game.html?id=224 "Game 224")

**Comment by ghost** [comment]
## Solution (TODO)
Don't count games against yourself at all

**Comment by Scriptim** [comment]
Closing this because the project has been discontinued.
