### ISSUE TITLE
Can I add a GUI?

### ISSUE THREAD

**Issue by theblaggy** [TheMorpheus407/BattleOfAI#25]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I just see these terminal outputs "Moving to (x,y)", but don´t really know what my AI / my opponents AI is doing.

**Describe the solution you'd like**
I want to add a GUI

**Describe alternatives you've considered**
An alternative would be to print out the complete board in terminal, but this wouldn´t be that better.

**Additional context**
![screen shot 2018-09-29 at 20 07 37](https://user-images.githubusercontent.com/36567291/46255661-1c5ca080-c48f-11e8-9e23-d92b1e605942.png)
![screen shot 2018-09-29 at 20 08 00](https://user-images.githubusercontent.com/36567291/46255662-1f579100-c48f-11e8-8375-6e4060fbec87.png)

**Comment by Scriptim** [comment]
I consider this redundant as there already exists a GUI:

https://battleofai.net/game.html?id={game_id}

You might want to extend the existing interface with a button to create a new game, for instance.

**Comment by theblaggy** [comment]
In the web interface I can't watch the games live. I always have to wait until they're finished, that´s really boring.

Also the web interface doesn't show the player ids and the score of the players.
In one of my first games, I played against an AI that was better than me, and I thought that's impossible, no one develops an AI in a few days, better than mine (I won the live event). Then I had to go to the API page (https://games.battleofai.net/api/) to see who I play against. In my GUI, I can directly see who I'm playing against.

**Comment by Scriptim** [comment]
> In the web interface I can't watch the games live. I always have to wait until they're finished, that´s really boring.

As far as I know, you can also check the current state of a game via the website while it is running. At the moment you have to reload the site regularly, but that would be something you could improve.

> Also the web interface doesn't show the player ids and the score of the players. [...]

That's what I meant by *"You might want to extend the existing interface"*.

Anyway, I find a second GUI pointless.

**Comment by theblaggy** [comment]
> You might want to extend the existing interface with a button to create a new game, for instance.

I´m only programming python and that stuff, but no web languages.

> Anyway, I find a second GUI pointless.

Yes, if you find someone who improves the web interface, then you´re right.

**Comment by ghost** [comment]
@the-blaggyS Please create an repository on your own. 
After that we can add a link to your repository in the README.
