### ISSUE TITLE
The Register button on the main site is not working.

### ISSUE THREAD

**Issue by ndsvw** [TheMorpheus407/BattleOfAI#3]
The link of the "Register" button (right next to "Register now to start fighting and climb the ladder.") does not show/open the sign-up modal.
<img width="996" alt="bildschirmfoto 2018-09-23 um 18 05 52" src="https://user-images.githubusercontent.com/21332313/45930086-598ad500-bf5b-11e8-9372-868bd361e1ae.png">

**Comment by felbinger** [comment]
@TheMorpheus407 I tried to fix this issue, but I don't understand how you open these modals (using a class?). data-toggle and data-target should work fine...

**Comment by TheMorpheus407** [comment]
Should be fixed.
